"""Stable public surface for Backoffice Copilot shared contracts."""

from .core import (
    AnalysisInput,
    BackendCandidate,
    BackendDeliveryStatus,
    BackendRequest,
    BackendResponse,
    BackofficeCopilotConfig,
    DefenseAuditEventRow,
    IssueContext,
    LlmReviewInput,
    LlmReviewOutput,
    LlmReviewTask,
    PipelineErrorList,
    PipelineIssue,
    PipelineWarningList,
    PostReviewGraphState,
    PostReviewRunContext,
    PostReviewRunInput,
    PostReviewRunRecord,
    PostReviewSessionResultRecord,
    ReviewResult,
    RunStatus,
    SessionAnalysis,
    SessionReviewResult,
    SessionSummary,
)
from .workflow import (
    BackofficeCopilotWorkflowApp,
    BackofficeCopilotWorkflowDependencies,
    WorkflowExecutionResult,
    build_backoffice_copilot_workflow,
)
from .adapters import (
    build_openai_review_adapter,
    build_openai_summary_adapter,
)

__all__ = [
    "AnalysisInput",
    "BackendCandidate",
    "BackendDeliveryStatus",
    "BackendRequest",
    "BackendResponse",
    "BackofficeCopilotConfig",
    "BackofficeCopilotWorkflowApp",
    "BackofficeCopilotWorkflowDependencies",
    "DefenseAuditEventRow",
    "IssueContext",
    "LlmReviewInput",
    "LlmReviewOutput",
    "LlmReviewTask",
    "PipelineErrorList",
    "PipelineIssue",
    "PipelineWarningList",
    "PostReviewGraphState",
    "PostReviewRunContext",
    "PostReviewRunInput",
    "PostReviewRunRecord",
    "PostReviewSessionResultRecord",
    "ReviewResult",
    "RunStatus",
    "SessionAnalysis",
    "SessionReviewResult",
    "SessionSummary",
    "WorkflowExecutionResult",
    "build_backoffice_copilot_workflow",
    "build_openai_review_adapter",
    "build_openai_summary_adapter",
]
