"""Event dictionary and per-state allowances for Defense PoC-0."""

from typing import Dict, List

from ..core import FlowState

from traffic_master_ai.common.models.events import EventType

# Canonical event names (Mapping STAGE_X to standard EventType)
FLOW_START = EventType.FLOW_START.value
FLOW_ABORT = EventType.FLOW_ABORT.value
FLOW_RESET = "FLOW_RESET" # Legacy or Common? I'll use a string for now if not in EventType

STAGE_1_ENTRY_ENABLED = EventType.ENTRY_ENABLED.value
STAGE_1_ENTRY_CLICKED = EventType.ENTRY_CLICKED.value

STAGE_2_QUEUE_SHOWN = EventType.QUEUE_SHOWN.value
STAGE_2_QUEUE_PASSED = EventType.QUEUE_PASSED.value

STAGE_3_CHALLENGE_APPEARED = EventType.CHALLENGE_APPEARED.value
STAGE_3_CHALLENGE_PASSED = EventType.CHALLENGE_PASSED.value
STAGE_3_CHALLENGE_FAILED = EventType.CHALLENGE_FAILED.value

STAGE_4_SECTION_LIST_READY = EventType.SECTION_LIST_READY.value
STAGE_4_SECTION_SELECTED = EventType.SECTION_SELECTED.value
STAGE_4_SECTION_EMPTY = EventType.SECTION_EMPTY.value

STAGE_5_SEATMAP_READY = EventType.SEATMAP_READY.value
STAGE_5_SEAT_SELECTED = EventType.SEAT_SELECTED.value
STAGE_5_SEAT_TAKEN = EventType.SEAT_TAKEN.value
STAGE_5_HOLD_FAILED = EventType.HOLD_FAILED.value
STAGE_5_CONFIRM_CLICKED = EventType.CONFIRM_CLICKED.value

STAGE_6_PAYMENT_PAGE_ENTERED = EventType.PAYMENT_PAGE_ENTERED.value
STAGE_6_PAYMENT_COMPLETED = EventType.PAYMENT_COMPLETED.value
STAGE_6_PAYMENT_ABORTED = EventType.PAYMENT_ABORTED.value

SIGNAL_TOKEN_MISMATCH = EventType.SIGNAL_TOKEN_MISMATCH.value
SIGNAL_REPETITIVE_PATTERN = EventType.SIGNAL_REPETITIVE_PATTERN.value

RISK_TIER_UPDATED = "RISK_TIER_UPDATED"

DEF_THROTTLED = EventType.DEF_THROTTLED.value
DEF_SANDBOXED = EventType.DEF_SANDBOXED.value
DEF_SANDBOX_RELEASED = "DEF_SANDBOX_RELEASED"
DEF_CHALLENGE_FORCED = EventType.DEF_CHALLENGE_FORCED.value
DEF_BLOCKED = EventType.DEF_BLOCKED.value

TIME_TIMEOUT = EventType.TIMEOUT.value
TIME_COOLDOWN_EXPIRED = "TIME_COOLDOWN_EXPIRED"

ALL_STATES: List[FlowState] = list(FlowState)

EVENT_ALLOWED_STATES: Dict[str, List[FlowState]] = {
    FLOW_START: [FlowState.S0],
    FLOW_ABORT: ALL_STATES,
    FLOW_RESET: ALL_STATES,
    STAGE_1_ENTRY_ENABLED: [FlowState.S1],
    STAGE_1_ENTRY_CLICKED: [FlowState.S1],
    STAGE_2_QUEUE_SHOWN: [FlowState.S2],
    STAGE_2_QUEUE_PASSED: [FlowState.S2],
    STAGE_3_CHALLENGE_APPEARED: [FlowState.S3],
    STAGE_3_CHALLENGE_PASSED: [FlowState.S3],
    STAGE_3_CHALLENGE_FAILED: [FlowState.S3],
    STAGE_4_SECTION_LIST_READY: [FlowState.S4],
    STAGE_4_SECTION_SELECTED: [FlowState.S4],
    STAGE_4_SECTION_EMPTY: [FlowState.S4],
    STAGE_5_SEATMAP_READY: [FlowState.S5],
    STAGE_5_SEAT_SELECTED: [FlowState.S5],
    STAGE_5_SEAT_TAKEN: [FlowState.S5],
    STAGE_5_HOLD_FAILED: [FlowState.S5],
    STAGE_5_CONFIRM_CLICKED: [FlowState.S5],
    STAGE_6_PAYMENT_PAGE_ENTERED: [FlowState.S6],
    STAGE_6_PAYMENT_COMPLETED: [FlowState.S6],
    STAGE_6_PAYMENT_ABORTED: [FlowState.S6],
    SIGNAL_TOKEN_MISMATCH: ALL_STATES,
    SIGNAL_REPETITIVE_PATTERN: ALL_STATES,
    RISK_TIER_UPDATED: ALL_STATES,
    DEF_THROTTLED: ALL_STATES,
    DEF_SANDBOXED: ALL_STATES,
    DEF_SANDBOX_RELEASED: ALL_STATES,
    DEF_CHALLENGE_FORCED: ALL_STATES,
    DEF_BLOCKED: ALL_STATES,
    TIME_TIMEOUT: ALL_STATES,
    TIME_COOLDOWN_EXPIRED: ALL_STATES,
}

__all__ = [
    "ALL_STATES",
    "EVENT_ALLOWED_STATES",
    "FLOW_ABORT",
    "FLOW_RESET",
    "FLOW_START",
    "STAGE_1_ENTRY_CLICKED",
    "STAGE_1_ENTRY_ENABLED",
    "STAGE_2_QUEUE_PASSED",
    "STAGE_2_QUEUE_SHOWN",
    "STAGE_3_CHALLENGE_APPEARED",
    "STAGE_3_CHALLENGE_FAILED",
    "STAGE_3_CHALLENGE_PASSED",
    "STAGE_4_SECTION_EMPTY",
    "STAGE_4_SECTION_LIST_READY",
    "STAGE_4_SECTION_SELECTED",
    "STAGE_5_CONFIRM_CLICKED",
    "STAGE_5_HOLD_FAILED",
    "STAGE_5_SEATMAP_READY",
    "STAGE_5_SEAT_SELECTED",
    "STAGE_5_SEAT_TAKEN",
    "STAGE_6_PAYMENT_ABORTED",
    "STAGE_6_PAYMENT_COMPLETED",
    "STAGE_6_PAYMENT_PAGE_ENTERED",
    "SIGNAL_REPETITIVE_PATTERN",
    "SIGNAL_TOKEN_MISMATCH",
    "RISK_TIER_UPDATED",
    "DEF_BLOCKED",
    "DEF_CHALLENGE_FORCED",
    "DEF_SANDBOXED",
    "DEF_SANDBOX_RELEASED",
    "DEF_THROTTLED",
    "TIME_COOLDOWN_EXPIRED",
    "TIME_TIMEOUT",
]
