"""Scenario schema definitions for Defense PoC-0 Acceptance Testing.

Defines dataclasses for scenario steps, scenarios, and step results.
"""

from dataclasses import dataclass, field
from typing import List, Optional

from ..core.states import DefenseTier, FailureCode, FlowState, TerminalReason
from ..signals.events import Event


@dataclass
class ScenarioStep:
    """A single step in a scenario.

    Attributes:
        input_event: The event to inject for this step.
        expected_state: Expected FlowState after step execution (None = no check).
        expected_tier: Expected DefenseTier after step execution (None = no check).
        expected_actions: Expected action types (e.g., ["THROTTLE", "BLOCK"]).
        description: Human-readable description of this step.
    """

    input_event: Event
    description: str
    expected_state: Optional[FlowState] = None
    expected_tier: Optional[DefenseTier] = None
    expected_actions: Optional[List[str]] = None


@dataclass
class Scenario:
    """A complete acceptance test scenario.

    Attributes:
        id: Unique scenario identifier (e.g., "SCN-01").
        title: Human-readable scenario title.
        steps: Ordered list of steps to execute.
    """

    id: str
    title: str
    steps: List[ScenarioStep]


@dataclass
class StepResult:
    """Result of executing a single scenario step.

    Contains actual execution results and mismatch information for debugging.
    Does not throw exceptions; mismatches are recorded in the mismatches list.

    Attributes:
        seq: Step sequence number (0-indexed).
        description: Step description from ScenarioStep.
        input_event_type: Type of the input event.
        from_state: FlowState before step execution.
        to_state: FlowState after step execution.
        from_tier: DefenseTier before step execution.
        to_tier: DefenseTier after step execution.
        planned_actions: Action types planned by ActionPlanner.
        emitted_event_types: Event types generated by Actuator (DEF_*, etc.).
        terminal_reason: Terminal reason if flow ended.
        failure_code: Failure code if flow failed.
        expected_state: Expected state (from step definition).
        expected_tier: Expected tier (from step definition).
        expected_actions: Expected actions (from step definition).
        mismatches: List of mismatch descriptions for debugging.
    """

    seq: int
    description: str
    input_event_type: str
    from_state: FlowState
    to_state: FlowState
    from_tier: DefenseTier
    to_tier: DefenseTier
    planned_actions: List[str] = field(default_factory=list)
    emitted_event_types: List[str] = field(default_factory=list)
    terminal_reason: Optional[TerminalReason] = None
    failure_code: Optional[FailureCode] = None
    expected_state: Optional[FlowState] = None
    expected_tier: Optional[DefenseTier] = None
    expected_actions: Optional[List[str]] = None
    mismatches: List[str] = field(default_factory=list)


__all__ = ["Scenario", "ScenarioStep", "StepResult"]
